[versions]
kotlin = "1.9.23"
jooq = "3.19.3"
kotstruct = "0.0.6"

ksp = "1.9.22-1.0.17"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

spring-boot = { id = "org.springframework.boot", version = "3.2.2" }

jooq = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }

openapi = { id = "org.openapi.generator", version = "7.2.0" }

[libraries]

kotstruct-api = { module = "com.github.vooft.kotstruct:kotstruct-api", version.ref = "kotstruct" }
kotstruct-generator = { module = "com.github.vooft.kotstruct:kotstruct-generator", version.ref = "kotstruct" }

jooq-core = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-liquibase = { module = "org.jooq:jooq-meta-extensions-liquibase", version.ref = "jooq" }
